version: '3'

services:
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MY_DATABASE_NAME}
      - MYSQL_USER=${MY_DATABASE_USER}
      - MYSQL_PASSWORD=${MY_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MY_DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql:/var/lib/mysql
  postgresql:
    image: postgres:15.1-alpine3.17
    environment:
      - POSTGRES_DB=${MY_DATABASE_NAME}
      - POSTGRES_USER=${MY_DATABASE_USER}
      - POSTGRES_PASSWORD=${MY_DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
    mysql:
        driver: local
    postgresql:
        driver: local
